-- AlterTable
ALTER TABLE `Post` MODIFY `status` ENUM('DRAFT', 'SCHEDULED', 'PENDING', 'PARTIALLY_PUBLISHED', 'PUBLISHED', 'FAILED') NOT NULL DEFAULT 'DRAFT';

-- AlterTable
ALTER TABLE `PostTarget` MODIFY `status` ENUM('DRAFT', 'SCHEDULED', 'PENDING', 'PARTIALLY_PUBLISHED', 'PUBLISHED', 'FAILED') NOT NULL DEFAULT 'SCHEDULED';
